# Generated by Django 5.1.5 on 2025-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
