# Generated by Django 5.1.5 on 2025-01-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_description_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
