# Generated by Django 5.1.5 on 2025-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Sobre'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Política de privacidade'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Categorias de perguntas'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'verbose_name_plural': 'Termos de uso'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
