# Generated by Django 5.1.5 on 2025-01-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_description_alter_question_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
    ]
