# Generated by Django 5.1.5 on 2025-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='about',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagem'),
        ),
    ]
