# Generated by Django 5.1.5 on 2025-01-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about_description_about_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='picture',
        ),
    ]
