# Generated by Django 5.1.5 on 2025-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_content_type_alter_comment_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('description', models.CharField(max_length=650, verbose_name='Descrição')),
                ('image', models.CharField(max_length=255, verbose_name='Imagem')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrossel',
            },
        ),
    ]
