# Generated by Django 5.1.5 on 2025-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.CharField(max_length=255, verbose_name='URL da imagem'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL de destino'),
        ),
    ]
