# Generated by Django 5.1.5 on 2025-02-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Dimensões recomendadas: 2160x740px', null=True, upload_to='articles/banners/', verbose_name='Imagem do banner'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Dimensões recomendadas: 468x272px', null=True, upload_to='articles/covers/', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='Dimensões recomendadas: 2160x740px', upload_to='carousels/', verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL de destino'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Dimensões recomendadas: 468x272px', null=True, upload_to='videos/covers/', verbose_name='Imagem de capa'),
        ),
    ]
