# Generated by Django 5.1.5 on 2025-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_carousel_image_alter_carousel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.CharField(blank=True, help_text='Dimensões recomendadas: 2160x740px', max_length=300, null=True, verbose_name='Imagem do banner'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Dimensões recomendadas: 468x272px', max_length=300, null=True, verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.CharField(max_length=300, verbose_name='URL da imagem'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Dimensões recomendadas: 468x272px', max_length=300, null=True, verbose_name='Imagem de capa'),
        ),
    ]
